### ISSUE TITLE
解决了吗

### ISSUE THREAD

**Issue by monsm** [h0730303779/SimpleWinForms_netcore-master#1]
The type initializer for 'DevExpress.Utils.Helpers.IconGuard' threw an exception.

InnerException {"Value cannot be null. (Parameter 'field')"} System.Exception {System.ArgumentNullException}

这个问题解决没

**Comment by hrx521** [comment]
我也遇到了同样的问题，没有解决

**Comment by hrx521** [comment]
似乎是dev版本过低的原因，v21.x不能支持.net6请参考这篇博文：https://stackoverflow.com/questions/61967838/netcore31-error-with-devexpress-with-winform

**Comment by hrx521** [comment]
还有dev官方文档也值得参考：https://docs.devexpress.com/WindowsForms/401191/dotnet-core-support
